name: download

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O test.csv http://spreadsheets.google.com/feeds/download/spreadsheets/Export?key=1nYxoeyVMJ2XBJJkEXEub0W0cKJLT-ZWo42t7Ox525aw&amp;exportFormat=csv&amp;gid=319990697
